apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: traced-serverless
  namespace: serverless-demo
spec:
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-go: "true"
    spec:
      containers:
        - image: gcr.io/knative-samples/helloworld-go
          env:
            - name: TARGET
              value: "Serverless with Istio Ambient!"
